### ISSUE TITLE
[Bug] Inaccurate time

### ISSUE THREAD

**Issue by vavavr00m** [JereKuusela/valheim-esp#9]
Some plants have inaccurate harvest timer, I don't remember which ones but when they're being monitored, the time for they to be harvestable is more than what the stated length is. I managed to take a screenshot of Lox pregnancy and it went over the supposed total time (120s) it takes for it to give birth to a calf - 150s is the current.

![image](https://github.com/JereKuusela/valheim-esp/assets/4675132/e5650cfb-423f-4124-b61b-7456fc7d881c)

**Comment by JereKuusela** [comment]
If you think the game doesn't work correctly that's something you should report to the Valheim developers.

My tool is for showing the data, not fixing the game bugs. 😁

**Comment by vavavr00m** [comment]
Thanks. Based on your response, I presume all data is retrieved from the game by ESP and no data shown by ESP is hardcoded. If that's the case, please close the issue.

**Comment by JereKuusela** [comment]
Yeah, it's bit of a dilemma what to exactly show. Currently it's mostly just game data.

I think all timers are more or less bugged in the game. But in normal gameplay it's not easy to notice.
